### ISSUE TITLE
duplicated rows in output

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#10]
see ChoquetH_29891935_GCST006065 - a user reported that the harmonised file contained duplicate records, whereas the source file, does not.

**Comment by ljwh2** [comment]
@jdhayhurst Has this now been fixed? See email to user Dana Fraser 3rd Dec "We'll add this file to the queue to get it reformatted and harmonised"

**Comment by jdhayhurst** [comment]
Yes this is done - closing
