### ISSUE TITLE
Harmonizing the studies from PMID: 37156999

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-sumstats-harmoniser#100]
Harmonising the data for [PMID:37156999](https://www.ebi.ac.uk/gwas/publications/37156999). Data are available [here](https://www.dropbox.com/scl/fi/9yyfkpa09x2bm3s56q1t2/liu-2022-east-asian-gwas.tar.gz?rlkey=96ezojmceei0ofe71z3pe7gm3&e=1&dl=0):

**Comment by jiyue1214** [comment]
Already been formatted and is waiting to be re-harmonised again after maintenance. 

Question: For each trait, author provide a EAS and EAS_EUR data. Inside the EAS_EUR data, it has fours sets of beta,p_value and se for meta, EAS, Finnish, and non-Finnish European. EAS data comes from the EAS data.

Finnish data comes from FinnGen, while non-Finnish European comes from PMID: [28067908](https://www.ebi.ac.uk/gwas/publications/28067908), which is available in the GWAS catalog already.

Should we split the EAS_EUR or not?

**Comment by ljwh2** [comment]
@eks-ebi to look into this

**Comment by jiyue1214** [comment]
After discussion, for the EAS_EUR data, we only keep the meta result and remove p_value, beta and se for eas, FIN and non-FIN European to avoid misleading results in the harmonised file.

**Comment by sajo-ebi** [comment]
Harmonisation not working due to codon maintenance related issues @jiyue1214 is looking into it

**Comment by jiyue1214** [comment]
GCST IDs of the study: 
GCST90446795	
GCST90446794	
GCST90446793	
GCST90446792	
GCST90432182	
GCST90292538

**Comment by jiyue1214** [comment]
@karatugo. Could I ask for your help that these studies were submitted successfully, but I cannot find the file either from depo folder "/hps/nobackup/parkinso/spot/gwas/data/sumstats/depo/staging/" nor staging folder "/nfs/production/parkinso/spot/gwas/prod/data/summary_statistics". (Not on FTP as well) Do you have any suggestions?

<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHl5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f449427f113864c8a70a3d7aa3bce6557fb7f1bb/Screenshot%202024-09-05%20at%2013.22.08.png" alt="Screenshot 2024-09-05 at 13.22.08.png" />

**Comment by karatugo** [comment]
Discussed on Slack, adding here too. 

The files were validated successfully on 28/29 Aug but they are not synced to staging FTP (probably due to post-maintenance Celery or scrontab errors). Unfortunately the files are removed from the validation directory, and therefore I suggest them to be submitted again.

**Comment by jiyue1214** [comment]
All files are harmonised. Can be closed

GCST90446792: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90446001-GCST90447000/GCST90446792/
GCST90446793: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90446001-GCST90447000/GCST90446793/
GCST90446794: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90446001-GCST90447000/GCST90446794/
GCST90446795: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90446001-GCST90447000/GCST90446795/
GCST90432182 : http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90432001-GCST90433000/GCST90432182/
GCST90292538: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90292001-GCST90293000/GCST90292538/
