### ISSUE TITLE
[FEATURE]: Better handling for user-input sumstats

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/gwas-sumstats-harmoniser#101]
### Is your feature request related to a problem? Please describe.

There are quite a few places where the pipeline breaks if there are no GCST ids, etc. E.g. with `publishDir`

### Describe the solution you'd like

A more general way to define the output folders and names. Currently it requires GCST to be in the filename, but it would be better if it read the gcst or output name from the `.yaml` so that you could put something custom.

**Comment by ljwh2** [comment]
This will be addressed in the next release, thanks for the suggestion
