### ISSUE TITLE
A new release of the harmonisation pipeline - v1.1.9 /v1.0.9

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-sumstats-harmoniser#108]
In this new release, we will include:

1. [handling z-score](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-sumstats-harmoniser/103)
2. improve the efficiency of the QC step
3. handling the user's input name which does not include GCST ([suggested by Sam](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-sumstats-harmoniser/101))
4. Output missing value as “#NA” in the final result (TBD)
5. Automatic version update in the running.log 
6. Documentation

**Comment by andreassteffen** [comment]
that's great news! When do you plan to release the new pipeline?

**Comment by jiyue1214** [comment]
@andreassteffen Thanks for your interest in our pipeline! We’re actively working on it, and while the documentation will take some time to complete, we’re aiming to release it as soon as possible.

When you mentioned that it "it does not work out of the box," could you please provide more details? For example, did the test model work but not on real data? Any specific challenges you encountered would be really helpful. Your experience could guide us in making the documentation more user-friendly and comprehensive.

I really appreciate your feedback!

**Comment by ljwh2** [comment]
@andreassteffen the new pipeline release is now in production with documentation available here: https://ebispot.github.io/gwas-sumstats-harmoniser-documentation/

Closing this ticket for now but please do send us any further details of issues you've encountered, and whether they are fixed in the latest release
