### ISSUE TITLE
How to cite harmoniser pipeline?

### ISSUE THREAD

**Issue by erskck-zi** [EBISPOT/gwas-sumstats-harmoniser#110]
Dear Team, 

Thanks for implementing this pipeline and making it publicly accessible. I'm using your pipeline to harmonise summary statistics in my PhD project. At the moment we are writing out manuscript and I would like to cite the pipeline, could you provide us an citation file?  
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Thanks and best wishes,
Ersoy

**Comment by ljwh2** [comment]
hi Ersoy, great to hear the harmonisation pipeline is useful to you! You might be interested to know that we are shortly releasing a new version that will be easier for external users to use on any file, and supports files with z-score and negative log p-value. 

For citation, right now you can use Buniello et al 2019 https://pubmed.ncbi.nlm.nih.gov/30445434/, and we also have a new manuscript coming out in Nucleic Acids Research (here in preprint: https://www.biorxiv.org/content/10.1101/2024.10.23.619767v1) that discusses recent updates to the pipeline. Thanks for checking!
