### ISSUE TITLE
Improve efficiency of pipeline

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#19]
The throughput of the pipeline is increasing as we are receiving more and more submissions.
A technology such a pyspark might help to speed up the pipeline. This may require a complete rewrite.

**Comment by jdhayhurst** [comment]
working with GDP to look at options

**Comment by sprintell** [comment]
Yue Testing at the moment with more files

**Comment by jdhayhurst** [comment]
Yue has made PR - @jdhayhurst review PR and release

**Comment by aoifemcm** [comment]
Yue has updated the documentation https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=162098787

**Comment by sprintell** [comment]
James is checking singularity ...
