### ISSUE TITLE
Rewrite and modify the snakemake pipeline with Nextflow

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#34]
- Input will be the files in the “ready to harmonise” directory - a wathcPath channel factory might be suitable for this
- The final harmonised files will also be sorted by genomic location, bgzipped and tabix indexed.
- Variants should be left-aligned and trimmed: https://genome.sph.umich.edu/wiki/Variant_Normalization and https://academic.oup.com/bioinformatics/article/31/13/2202/196142
- A log file reporting the reference source, dbSNP version, and the direction of palindromic SNPs are inferred from 10% sites or from whole sites. In some cases the file may not be eligible - this should be reported in the log
- The worlflow should be able to publish the harmonised file, the tabix file and the logs into a directory (one dir for each study, as is currently done) e.g. summary_statistics/study1/harmonised/<output from study1 workflow go here>  

more info:
https://docs.google.com/document/d/1b1g9PIUH6B688_aqBIaZulOtgCEnEXNcirJ1vUUmJq8/edit#

**Comment by aoifemcm** [comment]
@jdhayhurst Is variant normalisation (left align/trim)a requirement or blocker to operationalising the nextflow pipeline? Trying to get a sense of how essential it is at this stage
