### ISSUE TITLE
Query over GCST90010715 harmonisation

### ISSUE THREAD

**Issue by jinghuazhao** [EBISPOT/gwas-sumstats-harmoniser#51]
I am new to this repository and wonder if I can post a query here.

We are interested in use of GCST90010715 harmonisation results but it appears both the  hm_beta and hm_effect_allele_frequency variables were filled with missing values; could it be possible to have them? The GCST90010715_buildGRCh37.tsv file has most information though it only has MAF -- would gwas-sumstats-harmoniser be able to recover effective allele frequence (EAF), for instance? Since the sumstats were based on imputed genotypes I assume it is likely to be less involved?

Thank you!

**Comment by ljwh2** [comment]
Closing as response given by email
