### ISSUE TITLE
liftover with specified coordinate system

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#70]
With the new standard users will need to specify which coordinate system their summary stats are using (0-based or 1-based). 

The harmonisation pipeline should read this in from the metadata e.g. (https://github.com/EBISPOT/gwas-summary-statistics-standard/blob/7a83afa00e79b6603a97460eda114f85ed7b2da6/examples/0000123.tsv-meta.yaml#L23) and perform the liftover using the correct coordinate system.

**Comment by jiyue1214** [comment]
1. Solve the 1-base output after the liftover
2. talk with GWAS catalog community for insertions

**Comment by ljwh2** [comment]
@jdhayhurst It goes back to the question, if the analysis was performed without regards to ref and alt (which we know is quite common), is that information irretrievable? 
Just to be clear, is the 0 to 1 conversion currently solved in the harmonisation pipeline (I thought this had already been completed)? If not, is this a blocker to release of the new standard?

**Comment by sprintell** [comment]
@jdhayhurst pls check this
