### ISSUE TITLE
harmonisation sort is not working for chromosomes with no data 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#74]
if there is no data for a particular chromosome, the sort in harmonisation.nf fails as it doesn't account for that scenario.

**Comment by ljwh2** [comment]
What's the status of this one please, looks like it was moved to Done at one point? @jdhayhurst
Ideally, sumstats with missing data for at least one chromosome should fail validation (seems to be a relatively common error in old sumstats). I think we discussed that at one point but it was felt to be too computationally intensive.
