### ISSUE TITLE
 test it on a minimal dataset with a single command

### ISSUE THREAD

**Issue by yuj23** [EBISPOT/gwas-sumstats-harmoniser#77]
Hello! I am new to nextflow and i am trying to use this pipeline to harmonize my data.  I installed all the packages and environment needed and I tried to use command

```
./nextflow run -r master  EBISPOT/gwas-sumstats-harmoniser -profile test,conda
```
but it keeps throwing this error:
`N E X T F L O W  ~  version 23.04.3
Launching `https://github.com/EBISPOT/gwas-sumstats-harmoniser` [lethal_celsius] DSL2 - revision: 1291814b2f [master]
Harmonizing the file /nas/longleaf/home/bingxin/.nextflow/assets/EBISPOT/gwas-sumstats-harmoniser/test_data/GCST1.tsv
executor >  local (1)
executor >  local (1)
[dc/0c96ad] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)        [100%] 1 of 1, failed: 1 ✔
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:ten_percent_counts      -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:ten_percent_counts_sum  -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:generate_strand_counts  -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:summarise_strand_counts -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:main_harm:harmonization                 -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:main_harm:concatenate_chr_splits        -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:quality_control:qc                      -
[-        ] process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:quality_control:harmonization_log       -
[chr22,  is being harmonized]
[dc/0c96ad] NOTE: Process `NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)` terminated with an error exit status (1) -- Error is ignored`

The following is from the .nextflow.log file:

Aug-17 17:34:53.048 [Actor Thread 64] INFO  nextflow.script.BaseScript - [chr22,  is being harmonized]
Aug-17 17:34:53.151 [Actor Thread 64] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /nas/longleaf/home/bingxin/.nextflow/assets/EBISPOT/gwas-sumstats-harmoniser/test_data/GCST1.tsv-meta.yaml
Aug-17 17:34:53.155 [Actor Thread 64] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /nas/longleaf/home/bingxin/.nextflow/assets/EBISPOT/gwas-sumstats-harmoniser/test_data/GCST1.tsv
Aug-17 17:34:53.156 [Actor Thread 64] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /nas/longleaf/home/bingxin/.nextflow/assets/EBISPOT/gwas-sumstats-harmoniser/bin/map_to_build_nf.py
Aug-17 17:34:53.248 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Aug-17 17:34:53.252 [Task submitter] INFO  nextflow.Session - [f3/6f7b66] Submitted process > NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)
Aug-17 17:34:53.962 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1); status: COMPLETED; exit: 1; error: -; workDir: /proj/tengfei/user/yujue/harmonization/work/f3/6f7b662acae98b7befad74092a40ad]
Aug-17 17:34:53.966 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1); work-dir=/proj/tengfei/user/yujue/harmonization/work/f3/6f7b662acae98b7befad74092a40ad
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)` terminated with an error exit status (1)
Aug-17 17:34:53.971 [Task monitor] INFO  nextflow.processor.TaskProcessor - [f3/6f7b66] NOTE: Process `NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)` terminated with an error exit status (1) -- Error is ignored
Aug-17 17:34:53.980 [main] DEBUG nextflow.Session - Session await > all processes finished

Does anyone know how to solve this? Thank you!

**Comment by legaultmarc** [comment]
Hi,

I have been running into issues running the example as well. When I run the tool on the v1.1.1 release using the following command:

> nextflow run  EBISPOT/gwas-sumstats-harmoniser -profile test,singularity -r v1.1.1

I get the exact same error:

> [4b/5d0869] NOTE: Process `NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:major_direction:map_to_build (1)` terminated with an error exit status (1) -- Error is ignored

I am new to Nextflow as well and don't really know how to debug the specific tasks.

Thanks,

**Comment by smlmbrt** [comment]
I get the same error when I run it on my cluster:

**Comment by karatugo** [comment]
Yue fixed the issue. I tested the test command in Codon, looks good. 
Also, I submitted harmonisation job to test it on a real data. It should be done in 2 days. 

```
Details about the job can be found in the table below:
ID: 	21224886
Name: 	test_harmo_pre_gwas-ssf
```

**Comment by jiyue1214** [comment]
Hi, All.

Thank you for using the gwas-sumstats-harmoniser, and I apologize for the inconvenience caused by the bug.

We had a series of updates over the last few months due to various uses of our internal settings, which did not align in one release, causing the errors you encountered. In our recent release, v1.1.8, I hope you can run the harmoniser pipeline more smoothly.

Please feel free to share your error messages here, and we will be happy to assist you. Additionally, note that this pipeline has strict requirements for the input file. Please review the [gwas-ssf](https://github.com/EBISPOT/gwas-summary-statistics-standard) for the correct input file format.

Best regards
