### ISSUE TITLE
Minimal test dataset failing at the end when using singularity profile

### ISSUE THREAD

**Issue by Fabian-RY** [EBISPOT/gwas-sumstats-harmoniser#89]
On a fresh install of both nextflow (23.10.1.5891) and GWAS-sumstats-harmonizer, I tried to execute the pipeline with version v1.1.7, the latest release as of today, using the test profile and either docker or singularity

Using docker throws the error described in #77, failing at the start of the execution. 

nextflow run  EBISPOT/gwas-sumstats-harmoniser -r v1.1.7 -profile test,docker

Using singularity, however, gives a different error in the what i think is the last step. In fact, a folder with results named GCST1 with results. Harmonized sumstats are in the folder, but nextflow indicates:

nextflow run  EBISPOT/gwas-sumstats-harmoniser -r v1.1.7 -profile test,singularity

> NOTE: Process `NFCORE_GWASCATALOGHARM:GWASCATALOGHARM:quality_control:harmonization_log (1)` terminated with an error exit status (1) -- Error is ignored

The log gives what it seems to be two different errors

1) The script that fails is log_script.sh.

/bin/log_script.sh: line 87: [: missing `]'

It seems that there's a missing space in that if condition at that line, and it's present on master branch and v1.1.7 version. I tested it outside the container to check it and i think that is the cause. I can make a push request to fix it.

2) The other error is a bit more tricky. It seem sthat the library behind the gwas_metadata cannot load the file. 

> Traceback (most recent call last):
  File "/bin/gwas_metadata.py", line 71, in <module>
        main()
  File "/bin/gwas_metadata.py", line 60, in main
        m.from_file()
  File "/bin/gwas_metadata.py", line 21, in from_file
        self.update_metadata(self._meta_dict)
  File "/bin/gwas_metadata.py", line 34, in update_metadata
        self.metadata = self.metadata.parse_obj(self._meta_dict)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
        pydantic.error_wrappers.ValidationError: 1 validation error for SumStatsMetadata
date_metadata_last_modified
        field required (type=value_error.missing)

It seems that there is a field missing, data_metadata_last_modified. I executed the script outside the container, adding manually the missing field with dummy value (with format YYYY-MM-DD according to pydantic documentation) and it finished the script generating the new metadata. In the test yaml file there is a "date_last_modified" field but not the "data_metadata_last_modified" field

As said I can make a pull request to solve this problems.

Attached are the log files of that step and the general log of the pipeline.

[command.log.txt](https://github.com/EBISPOT/gwas-sumstats-harmoniser/files/15318211/command.log.txt)
[command.err.txt](https://github.com/EBISPOT/gwas-sumstats-harmoniser/files/15318212/command.err.txt)
[command.sh.txt](https://github.com/EBISPOT/gwas-sumstats-harmoniser/files/15318213/command.sh.txt)
[nextflow.log.txt](https://github.com/EBISPOT/gwas-sumstats-harmoniser/files/15318890/nextflow.log.txt)

**Comment by jiyue1214** [comment]
Hi Fabian,

Thank you for using the gwas-sumstats-harmoniser. I'm sorry for the bug you encountered.

The issue arises because one step of the harmonisation pipeline involves reading the meta-yaml file and updating it after harmonisation. The schema of the meta-yaml file is managed by another [repository](https://github.com/EBISPOT/gwas-sumstats-tools), which recently updated the schema, renaming date_last_modified to date_metadata_last_modified.

We have updated our test data accordingly and hope you won't encounter this issue using version v1.1.8. In the meantime, please feel free to contact us for more information.

Best regards,
