### ISSUE TITLE
Handling the ci_upper and ci_lower

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-sumstats-harmoniser#97]
Bug: ci_upper and ci_lower should be a float, instead of a boolean value. 66 studies were affected and they are being reharmonised.

**Comment by jiyue1214** [comment]
66 studies were affected by the error and I have reharmonised them.
GCST90128518
GCST90101802
GCST90101798
GCST90101801
GCST90101800
GCST90101799
GCST90101803
GCST90305767
GCST90406924
GCST90406925
GCST90281041
GCST90281042
GCST90276159
GCST90276158
GCST90276157
GCST90276160
GCST90320258
GCST90320259
GCST90320257
GCST90301397
GCST90301399
GCST90301398
GCST90278092
GCST90078323
GCST90078904
GCST90078960
GCST90078920
GCST90078961
GCST90078373
GCST90078317
GCST90079023
GCST90079288
GCST90079016
GCST90079010
GCST90079029
GCST90079317
GCST90079162
GCST90079329
GCST90079034
GCST90091239
GCST90078988
GCST90078927
GCST90078931
GCST90078912
GCST90078250
GCST90078902
GCST90078917
GCST90079068
GCST90079137
GCST90079045
GCST90079327
GCST90079043
GCST90079150
GCST90079273
GCST90079283
GCST90019040
GCST90017149
GCST90081511
GCST90081482
GCST90081506
GCST90081508
GCST90134285
GCST90165265
GCST90104038
GCST90104542
GCST90258619
@karatugo, could you please let me know if user replied us and told us that the example he showed is not in the list here? Thanks

**Comment by jiyue1214** [comment]
Yue revised the code and generated new release v1.0.9 and v1.1.9

**Comment by jiyue1214** [comment]
Should we follow up with the user if the new pipeline is working?

**Comment by karatugo** [comment]
Followed up on that now.

**Comment by karatugo** [comment]
User confirmed that the fix is working for them. Ticket can be closed.
